name: Deploy UMM

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_uri: ${{ steps.docker.outputs.image_uri }}
      instance_ips: ${{ steps.discover.outputs.ips }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        id: docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_REPO_NAME: umm-app
          IMAGE_TAG: latest
        run: |
          IMAGE_URI=$ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "::set-output name=image_uri::$IMAGE_URI"

      - name: Discover EC2 IPs from ASG by tag
        id: discover
        run: |
          echo "Looking up ASG name tagged with 'Name=umm-asg'..."

          ASG_NAME=$(aws autoscaling describe-auto-scaling-groups \
            --query 'AutoScalingGroups[?Tags[?Key==`Name` && Value==`umm-asg`]].AutoScalingGroupName' \
            --output text)

          if [ -z "$ASG_NAME" ]; then
            echo "ASG with Name=umm-asg tag not found."
            printf "ips=[]" >> $GITHUB_OUTPUT
            exit 1
          fi

          echo "Found ASG: $ASG_NAME"

          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$ASG_NAME" \
            --query "AutoScalingGroups[].Instances[?LifecycleState=='InService'].InstanceId" \
            --output text)

          if [ -z "$INSTANCE_IDS" ]; then
            echo "No InService instances found in ASG."
            printf "ips=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Found instance IDs: $INSTANCE_IDS"

          IPS=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_IDS \
            --query "Reservations[*].Instances[*].PrivateIpAddress" \
            --output text | tr '\n' ' ')

          echo "Found private IPs: $IPS"

          IP_JSON=$(echo "$IPS" | jq -Rs 'split(" ") | map(select(length > 0))' | jq -c '.')
          printf "ips=%s" "$IP_JSON" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to EC2 Instances
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance_ip: ${{ fromJson(needs.build-and-push.outputs.instance_ips) }}

    steps:
      - name: Debug matrix and image
        run: |
          echo "Deploying to ${{ matrix.instance_ip }}"
          echo "Using image: ${{ needs.build-and-push.outputs.image_uri }}"

      - name: Deploy to instance ${{ matrix.instance_ip }}
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.BASTION_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ matrix.instance_ip }}
          proxy_username: ec2-user
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop umm_app || true
            docker rm umm_app || true
            docker pull ${{ needs.build-and-push.outputs.image_uri }}
            docker run -d \
              --name umm_app \
              -p 80:80 \
              -e SECRET_KEY_BASE=super_secret_dummy_key \
              -e PHX_SERVER=true \
              -e PHX_HOST=0.0.0.0 \
              -e PORT=80 \
              --restart unless-stopped \
              ${{ needs.build-and-push.outputs.image_uri }}
